export const ImageUrlConstants = {
    yellowLock: require('../images/yellowLock.png'),
    greenCheck: require('../images/greenCheck.png'),
    clock: require('../images/clock.png'),
    fIcon2: require('../images/fIcon2.png'),
    truck: require('../images/truck.jpg'),
    backBtn: require('../images/backBtn.png'),
    forgotIcon: require('../images/forgotIcon.png'),
    dummyProfile1: require('../images/dummyProfile1.png'),
    home: require('../images/home.png'),
    phone: require('../images/phone.png'),
    invoice: require('../images/invoice.png'),
    more: require('../images/more.png'),
    back_icon: require('../images/back_icon.png'),
    bell: require('../images/bell.png'),
    onlinePayment:require('../images/online-payment.png'),
};
